---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DING.
--- DateTime: 2026-01-24 20:24
---
---优惠券id
local voucherId = ARGV[1]
---用户id
local userId = ARGV[2]


---库存key
local stockKey = 'seckill:stock:' .. voucherId
---订单key
local orderKey = 'seckill:order:' .. voucherId
---1.判断库存是否充足
if(tonumber(redis.call('GET',stockKey)) <=0) then
    --库存不足
    return 1
end
---2.判断用户是否下单
if(redis.call('SISMEMBER',orderKey,userId) ==1) then
    --用户已经下单
    return 2
end
---3.扣减库存
redis.call('incryby',stockKey,-1)
---4.下单
redis.call('SADD',orderKey,userId)
return 0